class GlucoseReading {
  final String? id;
  final String userId;
  final double reading;
  final String? timing;
  final String? notes;
  final String? photoUrl;
  final DateTime createdAt;

  GlucoseReading({
    this.id,
    required this.userId,
    required this.reading,
    this.timing,
    this.notes,
    this.photoUrl,
    DateTime? createdAt,
  }) : createdAt = createdAt ?? DateTime.now();

  factory GlucoseReading.fromJson(Map<String, dynamic> json) {
    return GlucoseReading(
      id: json['id'],
      userId: json['user_id'],
      reading: (json['reading'] as num).toDouble(),
      timing: json['timing'],
      notes: json['notes'],
      photoUrl: json['photo_url'],
      createdAt: DateTime.parse(json['created_at']),
    );
  }

  Map<String, dynamic> toJson() {
    final json = <String, dynamic>{
      'user_id': userId,
      'reading': reading,
    };
    
    // Only include optional fields if they have values
    if (timing != null && timing!.isNotEmpty) {
      json['timing'] = timing;
    }
    if (notes != null && notes!.isNotEmpty) {
      json['notes'] = notes;
    }
    if (photoUrl != null && photoUrl!.isNotEmpty) {
      json['photo_url'] = photoUrl;
    }
    
    // Note: created_at is typically auto-generated by Supabase, so we don't include it
    // If your table requires it, uncomment the line below:
    // json['created_at'] = createdAt.toIso8601String();
    
    return json;
  }
}